FROM node:14.10.1 as build

WORKDIR /app

COPY vue3/src src/
COPY vue3/public public/
COPY vue3/babel.config.js vue3/package-lock.json vue3/package.json vue3/vue.config.js ./

RUN npm ci
RUN npm run build

CMD ["npm", "run", "dev"]

FROM node:14.10.1 as production

WORKDIR /app

COPY --from=build /app/dist ./static
COPY server/api/user user
COPY server/package-lock.json server/package.json ./

RUN npm ci --production

CMD [ "npm", "start" ]
